config/routes.rb
Rails.application.routes.draw do
  mount Rswag::Ui::Engine => '/api-docs'
  mount Rswag::Api::Engine => '/api-docs'
  devise_for :users
  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create]
  end

  resources :posts, only: %i[index show new create destroy] do
    resources :comments, only: %i[new create destroy]
    resources :likes, only: :create
  end

  root 'users#index'

  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :users, only: %i[index show] do
        resources :posts, only: %i[index]
      end

      resources :posts, only: %i[index] do
        resources :comments, only: %i[index create]
      end
    end
  end
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new

    if user.admin?
      can :manage, :all
    else
      can :read, :all
      can :manage, Post, author_id: user.id
      can :manage, Comment, author_id: user.id
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  validates :text, presence: true, length: { maximum: 500 }

  after_commit :update_comment_counter, on: %i[create destroy]

  def update_comment_counter
    post.update(comments_counter: post.comments.count) unless post.destroyed?
  end
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :post
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'

  after_commit :update_like_counter, on: %i[create destroy]

  def update_like_counter
    post.update(likes_counter: post.likes.count) unless post.destroyed?
  end
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_many :comments, dependent: :destroy
  has_many :likes, dependent: :destroy

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :likes_counter, numericality: { greater_than_or_equal_to: 0 }

  after_commit :update_post_counter, on: %i[create destroy]

  def initialize(post_params)
    post_params.nil? ? super : super(post_params.merge(comments_counter: 0, likes_counter: 0))
  end

  def last_comments
    comments.last(5)
  end

  def update_post_counter
    author.update(posts_counter: author.posts.count) unless author.destroyed?
  end

  def likes_by(user)
    likes.where(author: user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable
  has_many :posts, foreign_key: 'author_id', dependent: :destroy
  has_many :comments, foreign_key: 'author_id', dependent: :destroy
  has_many :likes, foreign_key: 'author_id', dependent: :destroy

  validates :name, presence: true
  validates :posts_counter, numericality: { greater_than_or_equal_to: 0 }
  validates :email, presence: true, uniqueness: true

  def last_posts
    posts.last(3)
  end

  def admin?
    role == 'admin'
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ActionController::API
  load_and_authorize_resource

  def index
    @post = Post.find(params[:post_id])
    render json: { success: true, data: { comments: @post.comments } }
  rescue ActiveRecord::RecordNotFound
    render json: { success: false, message: 'Post not found' }
  end

  def create
    post = Post.find(params[:post_id])
    comment = post.comments.new(text: comment_params[:text], author: post.author)

    if comment.save
      render json: { success: true, message: 'Comment created' }
    else
      render json: { success: false, message: 'Comment not created' }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:text)
  end
end

app/controllers/api/v1/posts_controller.rb
class Api::V1::PostsController < ActionController::API
  load_and_authorize_resource

  def index
    @posts = User.find(params[:user_id]).posts
    render json: { success: true, data: { posts: @posts } }
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ActionController::API
  load_and_authorize_resource

  def index
    render json: { success: true, data: { users: User.all } }
  end

  def show
    render json: { success: true, data: { user: User.find(params[:id]) } }
  rescue ActiveRecord::RecordNotFound
    render json: { success: false, message: 'User is not found' }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password) }

    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  load_and_authorize_resource

  def new
    @post = post
    @comment = Comment.new
  end

  def create
    @comment = post.comments.create(comments_params.merge(author: current_user))

    if @comment.valid?
      redirect_to user_post_path(current_user, post), notice: t('.created')
    else
      redirect_to new_post_comment_path(post), alert: t('.not_created')
    end
  end

  def destroy
    comment = Comment.find(params[:id])

    if comment.destroy
      redirect_to user_post_path(comment.author, post), notice: t('.deleted')
      post.update_post_counter
    else
      redirect_to user_post_path(comment.author, post), alert: t('.not_deleted')
    end
  end

  private

  def comments_params
    params.require(:comment).permit(:text)
  end

  def post
    Post.find(params[:post_id])
  end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def create
    post = Post.includes(:likes).find(params[:post_id])
    likes = post.likes_by(current_user)

    likes.any? ? likes.each(&:destroy) : Like.create(post:, author: current_user)

    redirect_to user_posts_path(post.author)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  load_and_authorize_resource

  def index
    @user = User.includes(:posts, posts: [:author, :comments, { comments: :author }]).find(params[:user_id])
    @posts = @user.posts
  end

  def show
    @post = Post.includes(:comments).find(params[:id])
    @user = @post.author
  end

  def new
    @post = Post.new
    @user = current_user
  end

  def create
    if current_user.posts.create(post_params).valid?
      redirect_to user_posts_path(current_user), notice: t('.created')
    else
      redirect_to new_user_post_path(current_user), alert: t('.not_created')
    end
  end

  def destroy
    @post = Post.find(params[:id])

    if @post.destroy
      redirect_to user_posts_path(current_user), notice: t('.deleted')
    else
      redirect_to user_posts_path(current_user), alert: t('.not_deleted')
    end
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_comment.html.erb
<div>
  <%= comment.author.name %>: <%= comment.text %>
  <% if can? :destroy, comment%>
    <%= link_to t('common.delete'), post_comment_path(comment.post, comment), data: {
      turbo_method: :delete
    } %>
  <% end %>
</div>

app/views/comments/_form.html.erb
<%= form_with model: [@post, @comment] do |form| %>
  <% @comment.errors.full_messages.each do |error| %>
    <div><%= error %></div>
  <% end %>
  
  <div>
    <%= form.label :text%>
    <%= form.text_area :text%>
  </div>

  <%= form.submit %>
<% end %>

app/views/comments/new.html.erb
<h2><%=t('.title')%></h2>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AnthonyBlog</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/nav' %>
    <%= render 'shared/flash' %>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with model: [@post] do |form| %>
  <% @post.errors.full_messages.each do |error| %>
    <div><%= error %></div>
  <% end %>
  
  <div>
    <%= form.label :title%>
    <%= form.text_field :title%>
  </div>

  <div>
    <%= form.label :text%>
    <%= form.text_area :text%>
  </div>

  <%= form.submit %>
<% end %>

app/views/posts/_post.html.erb
<%= link_to user_post_path(post.author, post) do %>
  <article class="container">
    <div class="post__container">
      <h3><%= post.title %></h3>
      <% if local_assigns[:show_all_comments] %>
        <div class="post__counters">
          <%=t('common.comments')%>: <%= post.comments_counter %>, <%=t('common.likes')%>: <%= post.likes_counter %>
        </div>
      <% end %>

      <div class="float-buttons">
        <%= link_to post_likes_path(post), data: {
          turbo_method: :post
        } do %>
          <button> <%= t('.like') %> </button>
        <% end %>
        <% if can? :destroy, post %>
          <%= link_to post_path(post), data: {
            turbo_method: :delete
          } do %>
            <button> <%= t('.delete') %> </button>
          <% end %>
        <% end %>
      </div>

      <div>
        <%= post.text.truncate(20) if truncated_message %>
        <%= post.text unless truncated_message %>
      </div>
      <% if !local_assigns[:show_all_comments] %>
        <div class="post__counters">
          <%=t('common.comments')%>: <%= post.comments_counter %>, <%=t('common.likes')%>: <%= post.likes_counter %>
        </div>
      <% end %>
    </div>
  </article>
<% end %>

<% if local_assigns[:show_all_comments] && post.comments.any? %>
  <div class="container">
    <div><%= render partial: 'comments/comment', collection: post.comments %></div>
  </div>
<% end %>

<% if local_assigns[:show_lasts_comments] && post.last_comments.any? %>
  <div class="container">
    <div><%= render partial: 'comments/comment', collection: post.last_comments %></div>
  </div>
<% end %>

app/views/posts/index.html.erb
<%= render partial: 'users/user', locals: { user: @user } %>

<%= render partial: 'post', collection: @posts, locals: {truncated_message: true, show_lasts_comments: true} %>

<button><%=t('common.pagination')%></button>

<%= link_to user_path(@user.id) do %>
  <button><%=t('common.go_back')%></button>
<% end %>

app/views/posts/new.html.erb
<h2><%=t('.title')%></h2>

<%= render 'form' %>

app/views/posts/show.html.erb
<%= render partial: 'post', locals: {post: @post, truncated_message: false, show_all_comments: true} %>

<%= link_to new_post_comment_path(@post.id) do %>
  <button><%=t('.new_comment')%></button>
<% end %>

<%= link_to user_posts_path(@user.id) do %>
  <button><%=t('common.go_back')%></button>
<% end %>

app/views/shared/_flash.html.erb
<% if flash.key? :notice %>
  <div class="flash notice">
    <%= notice %>
  </div>
<% end %>
<% if flash.key? :alert %>
  <div class="flash alert">
    <%= alert %>
  </div>
<% end %>

app/views/shared/_nav.html.erb
<nav>
  <% if user_signed_in? %>
    <%= current_user.name %>
    <%= link_to 'Sign out', destroy_user_session_path, data: {
      turbo_method: :delete,
      turbo_confirm: "¿Are you sure you want to log out?"
    } %>
  <% elsif !devise_controller? %>
    <%= link_to 'Sign in', new_user_session_path %>
    <%= link_to 'Sign up', new_user_registration_path %>
  <% end %>
</nav>

app/views/users/_user.html.erb
<article class="container">
  <div class="user__picture">
  </div>
  <div class="user__body">
    <%= link_to user_path(user.id) do%>
      <div class="user__name">
        <%= user.name %>
      </div>
    <% end %>
    <div class="user__posts-count">
      <%=t('.number_of_posts')%>: <%= user.posts_counter %>
    </div>
  </div>
</article>

app/views/users/index.html.erb
<%= render partial: 'user', collection: @users %>

app/views/users/show.html.erb
<%= render partial: 'user', locals: { user: @user } %>

<article class="container">
  <div class="user__bio">
    <h3><%=t('common.bio')%></h3>
    <div>
      <%= @user.bio %>
    </div>
  </div>
</article>

<%= render partial: 'posts/post', collection: @user.last_posts, locals: {truncated_message: true, show_lasts_comments: true}%>

<%= link_to user_posts_path(@user.id) do %>
  <button><%=t('.see_all_posts')%></button>
<% end %>

<%= link_to new_user_post_path(@user.id) do %>
  <button><%=t('.new_post')%></button>
<% end %>

<%= link_to users_path do %>
  <button><%=t('common.go_back')%></button>
<% end %>